package com.ld.wsdl.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-03T21:09:02.588+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://server.wsdl.ld.com/", name = "WebService001")
@XmlSeeAlso({ObjectFactory.class})
public interface WebService001 {

    @WebMethod
    @Action(input = "http://server.wsdl.ld.com/WebService001/testWebServiceRequest", output = "http://server.wsdl.ld.com/WebService001/testWebServiceResponse")
    @RequestWrapper(localName = "testWebService", targetNamespace = "http://server.wsdl.ld.com/", className = "com.ld.wsdl.server.TestWebService")
    @ResponseWrapper(localName = "testWebServiceResponse", targetNamespace = "http://server.wsdl.ld.com/", className = "com.ld.wsdl.server.TestWebServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String testWebService(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
