package com.ld.wsdl.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-03T21:09:02.631+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "WebService001Service", 
                  wsdlLocation = "http://localhost:8888/webService/test?wsdl",
                  targetNamespace = "http://server.wsdl.ld.com/") 
public class WebService001Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.wsdl.ld.com/", "WebService001Service");
    public final static QName WebService001Port = new QName("http://server.wsdl.ld.com/", "WebService001Port");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/webService/test?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebService001Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8888/webService/test?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebService001Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebService001Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebService001Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WebService001Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebService001Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebService001Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WebService001
     */
    @WebEndpoint(name = "WebService001Port")
    public WebService001 getWebService001Port() {
        return super.getPort(WebService001Port, WebService001.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService001
     */
    @WebEndpoint(name = "WebService001Port")
    public WebService001 getWebService001Port(WebServiceFeature... features) {
        return super.getPort(WebService001Port, WebService001.class, features);
    }

}
