/**
 * Autogenerated by Thrift Compiler (0.8.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.soapsnake.thrift.license.pojo;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import java.util.*;

public class Person implements org.apache.thrift.TBase<Person, Person._Fields>, java.io.Serializable, Cloneable {
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Person");
    private static final org.apache.thrift.protocol.TField USER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("userName", org.apache.thrift.protocol.TType.STRING, (short) 1);
    private static final org.apache.thrift.protocol.TField USER_PHONE_FIELD_DESC = new org.apache.thrift.protocol.TField("userPhone", org.apache.thrift.protocol.TType.I32, (short) 2);
    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    // isset id assignments
    private static final int __USERPHONE_ISSET_ID = 0;

    static {
        schemes.put(StandardScheme.class, new PersonStandardSchemeFactory());
        schemes.put(TupleScheme.class, new PersonTupleSchemeFactory());
    }

    static {
        Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.USER_NAME, new org.apache.thrift.meta_data.FieldMetaData("userName", org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.USER_PHONE, new org.apache.thrift.meta_data.FieldMetaData("userPhone", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        metaDataMap = Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Person.class, metaDataMap);
    }

    public String userName; // required
    public int userPhone; // optional
    private BitSet __isset_bit_vector = new BitSet(1);
    private _Fields optionals[] = {_Fields.USER_PHONE};

    public Person() {
    }

    public Person(
            String userName) {
        this();
        this.userName = userName;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public Person(Person other) {
        __isset_bit_vector.clear();
        __isset_bit_vector.or(other.__isset_bit_vector);
        if (other.isSetUserName()) {
            this.userName = other.userName;
        }
        this.userPhone = other.userPhone;
    }

    public Person deepCopy() {
        return new Person(this);
    }

    @Override
    public void clear() {
        this.userName = null;
        setUserPhoneIsSet(false);
        this.userPhone = 0;
    }

    public String getUserName() {
        return this.userName;
    }

    public Person setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    public void unsetUserName() {
        this.userName = null;
    }

    /**
     * Returns true if field userName is set (has been assigned a value) and false otherwise
     */
    public boolean isSetUserName() {
        return this.userName != null;
    }

    public void setUserNameIsSet(boolean value) {
        if (!value) {
            this.userName = null;
        }
    }

    public int getUserPhone() {
        return this.userPhone;
    }

    public Person setUserPhone(int userPhone) {
        this.userPhone = userPhone;
        setUserPhoneIsSet(true);
        return this;
    }

    public void unsetUserPhone() {
        __isset_bit_vector.clear(__USERPHONE_ISSET_ID);
    }

    /**
     * Returns true if field userPhone is set (has been assigned a value) and false otherwise
     */
    public boolean isSetUserPhone() {
        return __isset_bit_vector.get(__USERPHONE_ISSET_ID);
    }

    public void setUserPhoneIsSet(boolean value) {
        __isset_bit_vector.set(__USERPHONE_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, Object value) {
        switch (field) {
            case USER_NAME:
                if (value == null) {
                    unsetUserName();
                } else {
                    setUserName((String) value);
                }
                break;

            case USER_PHONE:
                if (value == null) {
                    unsetUserPhone();
                } else {
                    setUserPhone((Integer) value);
                }
                break;

        }
    }

    public Object getFieldValue(_Fields field) {
        switch (field) {
            case USER_NAME:
                return getUserName();

            case USER_PHONE:
                return Integer.valueOf(getUserPhone());

        }
        throw new IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
     */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case USER_NAME:
                return isSetUserName();
            case USER_PHONE:
                return isSetUserPhone();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
        if (that == null)
            return false;
        if (that instanceof Person)
            return this.equals((Person) that);
        return false;
    }

    public boolean equals(Person that) {
        if (that == null)
            return false;

        boolean this_present_userName = true && this.isSetUserName();
        boolean that_present_userName = true && that.isSetUserName();
        if (this_present_userName || that_present_userName) {
            if (!(this_present_userName && that_present_userName))
                return false;
            if (!this.userName.equals(that.userName))
                return false;
        }

        boolean this_present_userPhone = true && this.isSetUserPhone();
        boolean that_present_userPhone = true && that.isSetUserPhone();
        if (this_present_userPhone || that_present_userPhone) {
            if (!(this_present_userPhone && that_present_userPhone))
                return false;
            if (this.userPhone != that.userPhone)
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        return 0;
    }

    public int compareTo(Person other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;
        Person typedOther = (Person) other;

        lastComparison = Boolean.valueOf(isSetUserName()).compareTo(typedOther.isSetUserName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetUserName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userName, typedOther.userName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetUserPhone()).compareTo(typedOther.isSetUserPhone());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetUserPhone()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userPhone, typedOther.userPhone);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Person(");
        boolean first = true;

        sb.append("userName:");
        if (this.userName == null) {
            sb.append("null");
        } else {
            sb.append(this.userName);
        }
        first = false;
        if (isSetUserPhone()) {
            if (!first) sb.append(", ");
            sb.append("userPhone:");
            sb.append(this.userPhone);
            first = false;
        }
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        if (userName == null) {
            throw new org.apache.thrift.protocol.TProtocolException("Required field 'userName' was not present! Struct: " + toString());
        }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bit_vector = new BitSet(1);
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    /**
     * The set of fields this struct contains, along with convenience methods for finding and manipulating them.
     */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        USER_NAME((short) 1, "userName"),
        USER_PHONE((short) 2, "userPhone");

        private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

        static {
            for (_Fields field : EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // USER_NAME
                    return USER_NAME;
                case 2: // USER_PHONE
                    return USER_PHONE;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        public static _Fields findByName(String name) {
            return byName.get(name);
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public String getFieldName() {
            return _fieldName;
        }
    }

    private static class PersonStandardSchemeFactory implements SchemeFactory {
        public PersonStandardScheme getScheme() {
            return new PersonStandardScheme();
        }
    }

    private static class PersonStandardScheme extends StandardScheme<Person> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, Person struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // USER_NAME
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.userName = iprot.readString();
                            struct.setUserNameIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // USER_PHONE
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.userPhone = iprot.readI32();
                            struct.setUserPhoneIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, Person struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.userName != null) {
                oprot.writeFieldBegin(USER_NAME_FIELD_DESC);
                oprot.writeString(struct.userName);
                oprot.writeFieldEnd();
            }
            if (struct.isSetUserPhone()) {
                oprot.writeFieldBegin(USER_PHONE_FIELD_DESC);
                oprot.writeI32(struct.userPhone);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class PersonTupleSchemeFactory implements SchemeFactory {
        public PersonTupleScheme getScheme() {
            return new PersonTupleScheme();
        }
    }

    private static class PersonTupleScheme extends TupleScheme<Person> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, Person struct) throws org.apache.thrift.TException {
            TTupleProtocol oprot = (TTupleProtocol) prot;
            oprot.writeString(struct.userName);
            BitSet optionals = new BitSet();
            if (struct.isSetUserPhone()) {
                optionals.set(0);
            }
            oprot.writeBitSet(optionals, 1);
            if (struct.isSetUserPhone()) {
                oprot.writeI32(struct.userPhone);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, Person struct) throws org.apache.thrift.TException {
            TTupleProtocol iprot = (TTupleProtocol) prot;
            struct.userName = iprot.readString();
            struct.setUserNameIsSet(true);
            BitSet incoming = iprot.readBitSet(1);
            if (incoming.get(0)) {
                struct.userPhone = iprot.readI32();
                struct.setUserPhoneIsSet(true);
            }
        }
    }

}

